# Generated by Django 5.0.6 on 2025-05-20 07:59

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("device", "0001_initial"),
        ("device_connector", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="device_connector",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="devices",
                to="device_connector.deviceconnector",
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("in_inventory", "In Inventory")],
                default="in_inventory",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="spacedevice",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="LorawanDevice",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("dev_eui", models.CharField(max_length=255, unique=True)),
                ("location", models.CharField(max_length=255)),
                (
                    "tags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=256), size=None
                    ),
                ),
                (
                    "device",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lorawan_devices",
                        to="device.device",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
