# Generated by Django 5.0.6 on 2025-06-05 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("device", "0002_device_device_connector_device_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lorawandevice",
            name="device",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lorawan_device",
                to="device.device",
            ),
        ),
    ]
