# Generated by Django 5.0.6 on 2025-08-28 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0004_create_connector_http_default'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='spacedevice',
            name='device_spac_slug_na_013783_idx',
        ),
        migrations.RemoveField(
            model_name='spacedevice',
            name='slug_name',
        ),
    ]
