# Generated by Django 5.0.6 on 2025-08-20 08:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("device", "0004_create_connector_http_default"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceTransformedData",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        editable=False, help_text="Actual device transformed data"
                    ),
                ),
                ("timestamp", models.DateTimeField(db_index=True)),
                ("source", models.CharField(blank=True, max_length=64, null=True)),
                ("metadata", models.JSONField(blank=True, null=True)),
                (
                    "device_reference",
                    models.CharField(default="unknown", max_length=255),
                ),
                ("device_eui", models.CharField(db_index=True, max_length=255)),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["device_eui", "timestamp"], name="device_timestamp_idx"
                    )
                ],
            },
        ),
    ]
