# Generated by Django 5.0.6 on 2025-08-25 10:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0005_devicetransformeddata"),
    ]

    operations = [
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("started_at", models.DateTimeField(db_index=True)),
                (
                    "ended_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "space_device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="device.spacedevice",
                    ),
                ),
            ],
        ),
    ]
