# Generated by Django 5.0.6 on 2025-11-20 03:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("device", "0008_remove_device_device_connector_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
    ]
