# Generated by Django 5.0.6 on 2025-11-20 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0008_remove_device_device_connector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='is_finished',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='trip',
            name='last_report',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='last_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='last_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='trip',
            name='ended_at',
        ),
    ]
