# Generated by Django 5.0.6 on 2025-12-02 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("device", "0010_update_trip"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="space_device",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="device.spacedevice"
            ),
        ),
    ]
