# Generated by Django 5.0.6 on 2025-12-18 02:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("device", "0011_alter_trip_space_device"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DeviceTransformedData",
        ),
    ]
