# Generated by Django 5.0.6

from django.db import migrations, models


def copy_device_model_id_to_device_model(apps, schema_editor):
    schema_editor.execute(
        """
        UPDATE device_device
        SET device_model = device_model_id
        WHERE device_model_id IS NOT NULL
        """
    )


class Migration(migrations.Migration):
    dependencies = [
        ("device", "0012_delete_devicetransformeddata"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="device_model",
            field=models.UUIDField(null=True, blank=True),
        ),
        migrations.RunPython(
            copy_device_model_id_to_device_model,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="device",
            name="device_model_id",
        ),
    ]
