# Generated by Django 5.0.6 on 2026-03-04 09:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("device", "0013_alter_device_model_to_charfield"),
    ]

    operations = [
        migrations.AddField(
            model_name="spacedevice",
            name="location",
            field=models.JSONField(
                null=True,
                blank=True,
            ),
        ),
    ]
