# Generated by Django 5.0.6 on 2026-04-16 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("building", "0001_initial"),
        ("device", "0014_device_location"),
        ("facility", "0001_initial"),
        ("placement", "0001_initial"),
        ("space", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="spacedevice",
            new_name="device__spa_name_3d5b69_idx",
            old_name="device_spac_name_04c052_idx",
        ),
        migrations.AddField(
            model_name="spacedevice",
            name="area",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="area_devices",
                to="building.area",
            ),
        ),
        migrations.AddField(
            model_name="spacedevice",
            name="facility",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="facility_devices",
                to="facility.facility",
            ),
        ),
        migrations.AddField(
            model_name="spacedevice",
            name="floor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="floor_devices",
                to="building.floor",
            ),
        ),
        migrations.AddField(
            model_name="spacedevice",
            name="position",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="position_devices",
                to="placement.position",
            ),
        ),
        migrations.AlterField(
            model_name="spacedevice",
            name="location",
            field=models.JSONField(
                blank=True,
                help_text='Location as JSON: {"latitude": <float>, "longitude": <float>}',
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="spacedevice",
            index=models.Index(fields=["space"], name="device__spa_space_i_20bd11_idx"),
        ),
        migrations.AddIndex(
            model_name="spacedevice",
            index=models.Index(
                fields=["device"], name="device__spa_device__434ba1_idx"
            ),
        ),
    ]
