# Generated by Django 5.0.6 on 2026-05-05 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("building", "0002_building_scene_asset"),
        (
            "device",
            "0015_rename_device_spac_name_04c052_idx_device__spa_name_3d5b69_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="spacedevice",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RenameIndex(
            model_name="spacedevice",
            new_name="device_spac_name_04c052_idx",
            old_name="device__spa_name_3d5b69_idx",
        ),
        migrations.RenameIndex(
            model_name="spacedevice",
            new_name="device_spac_space_i_242276_idx",
            old_name="device__spa_space_i_20bd11_idx",
        ),
        migrations.RenameIndex(
            model_name="spacedevice",
            new_name="device_spac_device__5c3187_idx",
            old_name="device__spa_device__434ba1_idx",
        ),
        migrations.AddField(
            model_name="spacedevice",
            name="building",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="building_devices",
                to="building.building",
            ),
        ),
    ]
