# Generated by Codex on 2026-08-07

from django.db import migrations, models


def copy_location_to_device(apps, schema_editor):
    SpaceDevice = apps.get_model("device", "SpaceDevice")
    Device = apps.get_model("device", "Device")
    copied_device_ids = set()

    for space_device in (
        SpaceDevice.objects.exclude(location__isnull=True)
        .order_by("device_id", "-updated_at")
        .only("device_id", "location", "updated_at")
        .iterator()
    ):
        if space_device.device_id in copied_device_ids:
            continue

        Device.objects.filter(id=space_device.device_id).update(
            location=space_device.location
        )
        copied_device_ids.add(space_device.device_id)


def copy_location_to_space_device(apps, schema_editor):
    SpaceDevice = apps.get_model("device", "SpaceDevice")
    Device = apps.get_model("device", "Device")

    for device in (
        Device.objects.exclude(location__isnull=True).only("id", "location").iterator()
    ):
        SpaceDevice.objects.filter(device_id=device.id).update(location=device.location)


class Migration(migrations.Migration):
    dependencies = [
        ("device", "0019_device_cells"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="location",
            field=models.JSONField(
                blank=True,
                help_text='Location as JSON: {"latitude": <float>, "longitude": <float>}',
                null=True,
            ),
        ),
        migrations.RunPython(copy_location_to_device, copy_location_to_space_device),
        migrations.RemoveField(
            model_name="spacedevice",
            name="location",
        ),
    ]
