# Generated by Codex on 2026-08-24

import uuid

import django.db.models.deletion
from django.db import migrations, models


def copy_device_fields_forward(apps, schema_editor):
    Device = apps.get_model("device", "Device")
    LorawanDevice = apps.get_model("device", "LorawanDevice")

    for lorawan_device in LorawanDevice.objects.values(
        "id",
        "device_id",
        "claim_code",
        "device__network_server_id",
    ).iterator():
        network_server_id = lorawan_device["device__network_server_id"]
        if network_server_id:
            LorawanDevice.objects.filter(id=lorawan_device["id"]).update(
                network_server_id=network_server_id
            )

        claim_code = lorawan_device["claim_code"]
        if claim_code:
            Device.objects.filter(id=lorawan_device["device_id"]).update(
                claim_code=claim_code
            )


def copy_device_fields_backward(apps, schema_editor):
    Device = apps.get_model("device", "Device")
    LorawanDevice = apps.get_model("device", "LorawanDevice")

    for lorawan_device in LorawanDevice.objects.values(
        "id",
        "device_id",
        "network_server_id",
        "device__claim_code",
    ).iterator():
        network_server_id = lorawan_device["network_server_id"]
        if network_server_id:
            Device.objects.filter(id=lorawan_device["device_id"]).update(
                network_server_id=network_server_id
            )

        claim_code = lorawan_device["device__claim_code"]
        if claim_code:
            LorawanDevice.objects.filter(id=lorawan_device["id"]).update(
                claim_code=claim_code
            )


class Migration(migrations.Migration):
    dependencies = [
        ("device", "0020_move_location_to_device"),
        ("network_server", "0004_alter_networkserver_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="claim_code",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="lorawandevice",
            name="network_server",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lorawan_devices",
                to="network_server.networkserver",
            ),
        ),
        migrations.CreateModel(
            name="APIDevice",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(max_length=100, unique=True),
                ),
                (
                    "device",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_device",
                        to="device.device",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RunPython(copy_device_fields_forward, copy_device_fields_backward),
        migrations.RemoveField(
            model_name="device",
            name="network_server",
        ),
        migrations.RemoveField(
            model_name="lorawandevice",
            name="claim_code",
        ),
    ]
