# Generated by Django 5.0.6 on 2024-11-12 03:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("country", "0001_initial"),
        ("device", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TtnDevice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("dev_eui", models.CharField(max_length=255)),
                ("join_eui", models.CharField(max_length=255)),
                ("phy_version", models.CharField(max_length=50)),
                (
                    "device",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ttn_device",
                        to="device.device",
                    ),
                ),
                (
                    "frequency",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ttn_devices",
                        to="country.lorafrequency",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["dev_eui"], name="ttn_device__dev_eui_03c2f7_idx"
                    )
                ],
            },
        ),
    ]
