# Generated by Django 5.0.6 on 2024-11-12 03:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChirpstackDevice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("dev_eui", models.CharField(max_length=255)),
                ("join_eui", models.CharField(max_length=255)),
                ("phy_version", models.CharField(max_length=50)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
