# Generated by Django 5.0.6 on 2024-11-12 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chirpstack_device", "0001_initial"),
        ("country", "0001_initial"),
        ("device", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chirpstackdevice",
            name="device",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chipstack_device",
                to="device.device",
            ),
        ),
        migrations.AddField(
            model_name="chirpstackdevice",
            name="frequency",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="chipstack_devices",
                to="country.lorafrequency",
            ),
        ),
        migrations.AddIndex(
            model_name="chirpstackdevice",
            index=models.Index(
                fields=["dev_eui"], name="chirpstack__dev_eui_629982_idx"
            ),
        ),
    ]
