# Generated by Django 5.0.6 on 2026-04-16 08:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Position",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("x", models.FloatField(default=0.0)),
                ("y", models.FloatField(default=0.0)),
                ("z", models.FloatField(default=0.0)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
