# Generated by Django 5.0.6 on 2026-04-16 08:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("space", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Facility",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "location",
                    models.JSONField(
                        blank=True,
                        help_text='Location as JSON: {"latitude": <float>, "longitude": <float>}',
                        null=True,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "scene_asset",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "space",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="space_facilities",
                        to="space.space",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["name"], name="facility_fa_name_1336c6_idx"),
                    models.Index(
                        fields=["space"], name="facility_fa_space_i_afa0a1_idx"
                    ),
                ],
            },
        ),
    ]
