# Generated by Django 5.0.6 on 2024-11-15 06:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DeviceManufacture",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("portal_url", models.URLField(blank=True, null=True)),
                ("national", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DeviceModel",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("alias", models.CharField(blank=True, max_length=255, null=True)),
                ("image_url", models.URLField(blank=True, null=True)),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("ttn_gateway", "TTN Gateway"),
                            ("ttn", "TTN"),
                            ("chirpstack", "Chirpstack"),
                            ("mqtt", "MQTT"),
                        ],
                        max_length=50,
                    ),
                ),
                ("default_config", models.JSONField(blank=True, null=True)),
                (
                    "manufacture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_models",
                        to="device_model.devicemanufacture",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["alias"], name="device_mode_alias_ed37e0_idx")
                ],
            },
        ),
    ]
