# Generated by Django 5.0.6 on 2025-05-20 07:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("network_server", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceConnector",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("connector_type", models.CharField(max_length=255)),
                ("status", models.CharField(max_length=255)),
                (
                    "network_server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_connector",
                        to="network_server.networkserver",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DeviceHttpConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("api_token", models.CharField(max_length=255)),
                ("address_url", models.CharField(max_length=255)),
                (
                    "device_connector",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_http_config",
                        to="device_connector.deviceconnector",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DeviceMqttConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("username", models.CharField(max_length=255)),
                ("password", models.CharField(max_length=255)),
                ("mqtt_broker", models.CharField(max_length=255)),
                (
                    "device_connector",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_mqtt_config",
                        to="device_connector.deviceconnector",
                    ),
                ),
            ],
        ),
    ]
