# Generated by Django 5.0.6 on 2025-05-23 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device_connector", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deviceconnector",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
