# Generated by Django 5.0.6 on 2025-05-28 02:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("device_connector", "0002_alter_deviceconnector_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deviceconnector",
            name="network_server",
            field=models.CharField(
                choices=[
                    ("ttn", "TTN"),
                    ("chirpstack", "Chirpstack"),
                    ("helium", "Helium"),
                ],
                default="ttn",
            ),
        ),
    ]
