# Generated by Django 5.0.6 on 2025-05-28 02:53

import apps.network_server.services
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device_connector", "0002_alter_deviceconnector_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deviceconnector",
            name="network_server",
            field=models.CharField(
                choices=apps.network_server.services.NetworkServer.choices,
                default=apps.network_server.services.NetworkServer["TTN"],
                max_length=255,
            ),
        ),
    ]
