# Generated by Django 5.0.6 on 2025-05-20 07:59

import django.contrib.postgres.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NetworkServer",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("logo", models.URLField(blank=True, null=True)),
                ("description", models.CharField(max_length=255)),
                (
                    "type_connect",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("mqtt_broker", "MQTT Broker"),
                                ("http_server", "HTTP Server"),
                            ],
                            max_length=50,
                            null=True,
                        ),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["name"], name="network_ser_name_f2d1be_idx")
                ],
            },
        ),
    ]
