# Generated by Django 5.0.6 on 2025-05-28 02:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("device_connector", "0003_alter_deviceconnector_network_server"),
        ("network_server", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="NetworkServer",
        ),
    ]
