# Generated by Django 5.0.6 on 2026-05-15 09:31

import posixpath
from urllib.parse import unquote, urlsplit

from django.db import migrations, models


def normalize_network_server_logo(apps, schema_editor):
    NetworkServer = apps.get_model("network_server", "NetworkServer")
    default_logos = {
        "chirpstack": "chirp_stack.png",
        "ttn": "ttn.png",
        "helium": "helium.png",
    }
    network_servers_to_update = []

    for network_server in NetworkServer.objects.exclude(logo__isnull=True):
        raw_logo = (network_server.logo or "").strip()
        normalized_logo = raw_logo
        normalized_name = (network_server.name or "").strip().lower()

        if normalized_name in default_logos:
            normalized_logo = default_logos[normalized_name]
        elif not raw_logo:
            normalized_logo = None
        else:
            parsed_logo = urlsplit(raw_logo)
            path = (
                parsed_logo.path
                if parsed_logo.scheme or parsed_logo.netloc
                else raw_logo
            )
            filename = unquote(posixpath.basename(path.strip()))

            if filename:
                normalized_logo = filename
            elif parsed_logo.scheme or parsed_logo.netloc:
                normalized_logo = None

        if normalized_logo != network_server.logo:
            network_server.logo = normalized_logo
            network_servers_to_update.append(network_server)

    if network_servers_to_update:
        NetworkServer.objects.bulk_update(network_servers_to_update, ["logo"])


class Migration(migrations.Migration):
    dependencies = [
        ("network_server", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="networkserver",
            name="logo",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RunPython(
            normalize_network_server_logo,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
