# Generated by Django 5.0.6 on 2025-05-20 07:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("device_model", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="devicemodel",
            name="device_type",
        ),
    ]
