# Generated by Django 5.0.6 on 2025-05-22 09:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("device_model", "0002_remove_devicemodel_device_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="devicemodel",
            name="device_type",
            field=models.CharField(
                blank=True, choices=[("lorawan", "LoRaWAN")], max_length=255, null=True
            ),
        ),
    ]
