# Generated by Django 5.0.6 on 2025-09-25 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("device_model", "0003_devicemodel_device_type"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="devicemodel",
            name="device_mode_alias_ed37e0_idx",
        ),
        migrations.RemoveField(
            model_name="devicemodel",
            name="alias",
        ),
        migrations.AlterField(
            model_name="devicemodel",
            name="manufacture",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="device_models",
                to="device_model.devicemanufacture",
            ),
        ),
        migrations.AddIndex(
            model_name="devicemodel",
            index=models.Index(fields=["name"], name="device_mode_name_d69fc8_idx"),
        ),
    ]
