# Generated by Django 5.0.6 on 2025-12-13 11:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "device_model",
            "0004_remove_devicemodel_device_mode_alias_ed37e0_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="devicemodel",
            name="key_feature",
            field=models.CharField(
                blank=True,
                choices=[
                    ("water_level_sensor", "Water Level Sensor"),
                    ("multi_sensor_tracker", "Multi Sensor Tracker"),
                ],
                default="multi_sensor_tracker",
                max_length=255,
                null=True,
            ),
        ),
    ]
