# Generated by Django 5.0.6 on 2025-05-20 07:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("device_connector", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("enable", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=255)),
                ("parameters", models.JSONField()),
                ("resource_opts", models.JSONField()),
                ("type", models.CharField(max_length=255)),
                (
                    "device_connector",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_resource",
                        to="device_connector.deviceconnector",
                    ),
                ),
            ],
        ),
    ]
