# Generated by Django 5.0.6 on 2025-05-20 07:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("action", "0001_initial"),
        ("resource", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Definition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("rule_id", models.CharField(max_length=255)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("sql", models.CharField(max_length=255)),
                (
                    "action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_rule",
                        to="action.action",
                    ),
                ),
                (
                    "resource",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_rule",
                        to="resource.resource",
                    ),
                ),
            ],
        ),
    ]
