# Generated by Django 5.0.6 on 2024-11-20 07:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("device", "0001_initial"),
        ("frequency", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TtnGateway",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("gateway_eui", models.CharField(max_length=255)),
                (
                    "device",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ttn_gateway",
                        to="device.device",
                    ),
                ),
                (
                    "frequency",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ttn_gateways",
                        to="frequency.lorafrequency",
                    ),
                ),
            ],
        ),
    ]
