# Generated by Django 5.0.6 on 2026-04-16 08:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("space", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Building",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "location",
                    models.JSONField(
                        blank=True,
                        help_text='Location as JSON: {"latitude": <float>, "longitude": <float>}',
                        null=True,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "space",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="space_buildings",
                        to="space.space",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Floor",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("level", models.IntegerField(default=1)),
                (
                    "scene_asset",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="building_floors",
                        to="building.building",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Area",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("area_type", models.CharField(max_length=50)),
                (
                    "scene_asset",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "floor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="floor_areas",
                        to="building.floor",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="building",
            index=models.Index(fields=["name"], name="building_bu_name_a8dfe7_idx"),
        ),
        migrations.AddIndex(
            model_name="building",
            index=models.Index(fields=["space"], name="building_bu_space_i_08b843_idx"),
        ),
        migrations.AddIndex(
            model_name="floor",
            index=models.Index(fields=["name"], name="building_fl_name_4eee17_idx"),
        ),
        migrations.AddIndex(
            model_name="floor",
            index=models.Index(
                fields=["building"], name="building_fl_buildin_2e8b5a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="area",
            index=models.Index(fields=["name"], name="building_ar_name_c43450_idx"),
        ),
        migrations.AddIndex(
            model_name="area",
            index=models.Index(fields=["floor"], name="building_ar_floor_i_c9e936_idx"),
        ),
        migrations.AddIndex(
            model_name="area",
            index=models.Index(
                fields=["area_type"], name="building_ar_area_ty_3f58bf_idx"
            ),
        ),
    ]
