# Generated by Django 5.0.6 on 2026-05-05 08:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("building", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="building",
            name="scene_asset",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
