"""
Django settings for device_service project.

Generated by 'django-admin startproject' using Django 3.2.14.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

import os
from pathlib import Path

# Basic settings
SERVICE_NAME = "device"
BASE_DIR = Path(__file__).resolve().parent.parent
DEBUG = os.getenv("ENV", default="dev") == "dev"
SECRET_KEY = os.getenv(
    "SECRET_KEY", "django-insecure-*$0b8ibx7uzk45cm+fxw7*jj(yzi2ye!l4+!dnyxa-u-nbuz=q"
)
ALLOWED_HOSTS = [os.getenv("ALLOWED_HOSTS", "*")]
HOST = os.getenv("HOST", "http://localhost:8000/")
DEFAULT_TENANT_HOST = os.getenv("DEFAULT_TENANT_HOST", "localhost")

# Application definition
SHARED_APPS = [
    "django_tenants",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "whitenoise.runserver_nostatic",
    "django.contrib.staticfiles",
    "rest_framework",
    "corsheaders",
    "drf_yasg",
    "common.apps.organization",
    "common.apps.celery_autoreload",
]

TENANT_APPS = [
    "django.contrib.auth",
    "common.apps.space",
    "apps.device_model",
    "apps.device",
    "apps.device_connector",
    "apps.rule.resource",
    "apps.rule.definition",
    "apps.rule.action",
    "apps.network_server",
]

INSTALLED_APPS = SHARED_APPS + [app for app in TENANT_APPS if app not in SHARED_APPS]

MIDDLEWARE = [
    "common.middlewares.tenant_middleware.TenantMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "common.middlewares.query_alert_middleware.QueryAlertMiddleware",
]

ROOT_URLCONF = "device_service.urls"
WSGI_APPLICATION = "device_service.wsgi.application"
DATABASE_ROUTERS = ("django_tenants.routers.TenantSyncRouter",)

# Templates
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

# Database
DATABASES = {
    "default": {
        "ENGINE": "django_tenants.postgresql_backend",
        "NAME": os.getenv("DB_NAME", "spacedf_device_service"),
        "USER": os.getenv("DB_USERNAME", "postgres"),
        "PASSWORD": os.getenv("DB_PASSWORD", "postgres"),
        "HOST": os.getenv("DB_HOST", "localhost"),
        "PORT": "5432",
    }
}

# Internationalization
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_L10N = True
USE_TZ = True

# Static files
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
STATIC_URL = "/device/static/"
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "<app_name>/static"),
    os.path.join(BASE_DIR, "static"),
)

# Default primary key field type
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Rest framework
REST_FRAMEWORK = {
    "EXCEPTION_HANDLER": "common.errors.exception_handler.custom_exception_handler",
}

# Swagger settings
SWAGGER_SETTINGS = {
    "SECURITY_DEFINITIONS": {
        "User ID": {"type": "apiKey", "name": "X-User-ID", "in": "header"},
        "Space": {"type": "apiKey", "name": "X-Space", "in": "header"},
    }
}

# Multi-tenants
TENANT_MODEL = "organization.Organization"
TENANT_DOMAIN_MODEL = "organization.Domain"
SHOW_PUBLIC_IF_NO_TENANT_FOUND = True
PUBLIC_SCHEMA_URLCONF = "device_service.urls_public"

# Celery
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_ACKS_LATE = True
CELERYD_PREFETCH_MULTIPLIER = 1
CELERY_APP = "device_service.celery.app"
CLONE_MODELS = [
    "space",
]
CELERY_TASKS = [
    "common.apps.organization",
    "common.apps.space",
]
CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", "amqp://guest:guest@localhost")

# Middleware settings
PUBLIC_PATHS = ["/api/.well-known", "/docs", "/static"]

# CORS settings
CORS_ALLOWED_ORIGINS = os.getenv("CORS_ALLOWED_ORIGINS", "http://localhost:3000").split(
    ","
)

# EMQX
EMQX_HOST = os.getenv("EMQX_HOST", "http://emqx:18083/api/v5")
USERNAME = os.getenv("USERNAME", "admin")
PASSWORD = os.getenv("PASSWORD", "public")
